### ISSUE TITLE
Questions about version of Waymo Open Dataset?

### ISSUE THREAD

**Issue by wzmsltw** [tusen-ai/SimpleTrack#27]
Hi, 

Thanks for releasing codes! During running pre-processing in WOD, I am confused that which version of WOD should be used. Is 1.2.0 or 1.3.0 ?

**Comment by ziqipang** [comment]
I guess both are fine. To be honest, I am not sure about how Waymo evolves these days. However, I guess these newer versions are compatible with 3D MOT, since the upgrades are mainly related to trajectory prediction, occupancy flow forecasting, camera-based 3D detection, etc. Maybe you can try 1.3.0 first?
